version: "3.0"
services:
    jenkins:
        container_name: jenkins
        image: jenkins/jenkins
        ports:
            - 8080:8080
        volumes:
            - $PWD/jenkins_home:/var/jenkins_home
            - "/etc/localtime:/etc/localtime"
        networks:
            - net
    remote_host:
        container_name: remote-host
        image: remote-host
        volumes:
            - "/etc/localtime:/etc/localtime"
        build:
            context: centos7
        networks:
            - net
    db_host:
        container_name: db
        image: mysql:5.7
        volumes:
            - "/etc/localtime:/etc/localtime"
        environment:
            - "MYSQL_ROOT_PASSWORD=xxxxxxxxxx"
        volumes:
            - "$PWD/db_data:/var/lib/mysql"
        networks:
            - net

networks:
    net:
